### ISSUE TITLE
Variable Positioning

### ISSUE THREAD

**Issue by obp3ter** [naari3/offers-hud#26]
I would love it if I could move it a bit down (/right) so that it's not below a more important overlay. I was thinking of something like how other mods do it, with corner presets and x&y offsets after that.

**Comment by mrniddala** [comment]
Hello, I really love that idea. And I would even add scaling 🥰
Greetings.

**Comment by naari3** [comment]
I have tried a small implementation for config. This requires you have modmenu, but you can set the X,Y offset of the HUD in config.

but, I haven't been able to test it yet because I can't run Minecraft due to personal GPU issues.

**Comment by obp3ter** [comment]
Later today I'll download it or pull the branch and build it and try it out, I'll tell you how it goes.

**Comment by naari3** [comment]
This time I simply allowed x,y values to be put in the config, so if you know of a better way or implementation of this, please let me know :pray:

or is this enough?

**Comment by naari3** [comment]
This time I just simply made it so I can put x,y values in the config, so if you know of a better way or an implementation of that, please let me know :pray:

or is this enough?

**Comment by naari3** [comment]
Here is artifacts of latest commit.
[Compiled artifacts for b52b5ba6609914fa1ceaf037866937d43ec6740b.zip](https://github.com/naari3/offers-hud/files/8935806/Compiled.artifacts.for.b52b5ba6609914fa1ceaf037866937d43ec6740b.zip)

**Comment by obp3ter** [comment]
So I checked it out, and it is enough for what I really needed, but I noticed a problem. When I try to edit the x value, it Alt+Tabs out of the game.

**Comment by obp3ter** [comment]
It swiyches out of the game when I click on th input field in the modmenu settings. But only for the x value not for the other one.

**Comment by naari3** [comment]
@obp3ter Just to be sure, could you tell me what version of modmenu you have?

and, I did not make it clear due to my mistake, but perhaps the Cloth Config API also needed to be installed. Please let me know the version of this as well.

**Comment by obp3ter** [comment]
Cloth Config API 7.0.72 & Mod Menu 4.0.0

**Comment by naari3** [comment]
@obp3ter hmm, I still couldn't reproduce it. It may be a bug in Cloth Conifg or something?

I think it is unlikely that this is a bug in OffersHUD unless it is fundamentally wrong, since OffersHUD only uses a simple usage.

https://github.com/naari3/offers-hud/blob/main/src/main/java/net/naari3/offershud/config/ModConfig.java
https://github.com/naari3/offers-hud/blob/main/src/main/java/net/naari3/offershud/config/ModMenuIntegration.java

I will try to reproduce tomorrow on another environment(macOS).

**Comment by naari3** [comment]
I still have my doubts, but I will merge the PRs for now. https://github.com/naari3/offers-hud/pull/27

**Comment by obp3ter** [comment]
Well, I'm using Windows so I don't think the mac testing is relevant for this, I'll reinstall everything, maybe something helps.

**Comment by naari3** [comment]
@mrniddala I also implemented scaling features at #28

**Comment by obp3ter** [comment]
With this version, I don't have the problem anymore, and I don't see why it changed.

**Comment by naari3** [comment]
Released on CurseForge, modrinth and GitHub Releases. thanks! @obp3ter @mrniddala 

https://www.curseforge.com/minecraft/mc-mods/offershud/files/3841741
https://modrinth.com/mod/offershud/version/v1.1.0
https://github.com/naari3/offers-hud/releases/tag/v1.1.0
