### ISSUE TITLE
Name tag is constantly applied to villager

### ISSUE THREAD

**Issue by TheEvilM** [naari3/offers-hud#31]
If you look at a villager with a name tag in hand, it will automatically apply

![image](https://user-images.githubusercontent.com/44786782/205329256-19f8ba5e-a340-4bf9-abc8-b3ddcaf878dc.png)

**Comment by naari3** [comment]
Oh, that's right. I'll think about it, but I don't know if there's a way to determine if the item I'm holding can be used by a villager.
