### ISSUE TITLE
Incompatibility with Stylish effects mod [1.19.2]

### ISSUE THREAD

**Issue by MrTonyNeon** [naari3/offers-hud#32]
[https://www.curseforge.com/minecraft/mc-mods/stylish-effects](Stylish effects) 
possibly using `renderStatusEffectOverlay` аnd therefore, while this mod is installed, OffersHUD is not displayed. But there is no disabling this function in the mod config. Is it possible for me to fix this somehow?

**Comment by MrTonyNeon** [comment]
[stylisheffects-client.txt](https://github.com/naari3/offers-hud/files/10460674/stylisheffects-client.txt)
attaching the config file if that helps.

**Comment by naari3** [comment]
hmm, I took a quick look at [stylish-effects](https://github.com/Fuzss/stylisheffects), but I cannot find where is renderStatusEffectOverlay is used.
There may be other causes that I don't know about, so I need to investigate.

**Comment by naari3** [comment]
@MrTonyNeon Sorry it's been over a year since I've replied.
You may not be using both this mod and Stylish anymore, but I changed the rendering method in 1.4.0. This is only compatible with 1.20, but if you are using both mods, could you please try to see if it works correctly?

**Comment by naari3** [comment]
If this occurs again, feel free to reopen this!
