### ISSUE TITLE
HUD causes other interfaces to close

### ISSUE THREAD

**Issue by BlackQuests** [naari3/offers-hud#35]
Currently, the offers HUD causes any other interface to be closed whenever it is shown.

For example:
When a player opens a chest and a villager walks in front of the player, it will close the chest interface in order to show the offers HUD.

I feel the HUD should not be shown if the player currently has another interface open. (This includes anvils, crafting tables, smithing tables, etc.) since this can be quite annoying with a lot of villagers around.

What is your opinion on this? I'm willing to make a pull request if I can devise a fix.

**Comment by naari3** [comment]
Absolutely!!

I think this should be fixed. and if you're up for tackling this issue, that would be awesome!

The way the mod works is to force an Interact at the time of focus on the Merchant to get the offers packets from the server.
If we can get some status of whether screen is open or not, it would be good to have a patch to prevent it from during that time.

for example: if `config.enabled` is false, return early.
https://github.com/naari3/offers-hud/blob/ddfc0d7d8647d790dce8d1d03e32bad23cf3c65e/src/main/java/net/naari3/offershud/OffersHUD.java#L41-L42

**Comment by naari3** [comment]
@BlackQuests If you want to create a PR, you are welcome! If you're not that interested, I'll deal with it here. How about that?

**Comment by BlackQuests** [comment]
> @BlackQuests If you want to create a PR, you are welcome! If you're not that interested, I'll deal with it here. How about that?

Hi! Sorry, I currently don't have the time or motivation to pick this up (recently stopped playing again haha). Feel free to take it on yourself!
I might get back into minecraft again in the near future, if the issue is still open I will consider looking into it!

**Comment by naari3** [comment]
@BlackQuests v1.3.2 has been released which fixes this issue! Thank you for the report!
