### ISSUE TITLE
mod not working on Feather Fabric mode

### ISSUE THREAD

**Issue by legendvenom12492** [naari3/offers-hud#38]
mod doesnt work on the featherclient tried several times still no progress

**Comment by naari3** [comment]
@legendvenom12492 Can you try it once to see if it works directly with Fabric without going through the Feather Client?

**Comment by naari3** [comment]
@legendvenom12492 Also, when you make an issue in a place like this, "How did it not work?" should be written. For example, "it didn't show up in the mod list in the first place" or "the instance stopped starting" or "I was able to install the mod, but it didn't show up HUD.".

**Comment by naari3** [comment]
it seems like obsolete. if you think this issue still be needed, feel free to reopen this issue.
