### ISSUE TITLE
Not affect special pricing

### ISSUE THREAD

**Issue by naari3** [naari3/offers-hud#7]
## expected

If villager is being to special pricing, required emeralds counts should be respected.

## actual

Display original prices

**Comment by gXLg** [comment]
@naari3 Minecraft should have a method called "TradeOffer#getAdjustedFirstBuyItem", which returns the adjusted price. In versions from 1.19.3 it's called "getDisplayedFirstBuyItem".
The same applies for the second buy item. The naming is similar.

**Comment by naari3** [comment]
@gXLg Thank you so much for information!! I haven't looked at the code around here recently, but I remember when I looked at it a long time ago, calling this method would return the regular price.

I thought it was probably due to packet exchange between the server and client side, but it may simply have been a misunderstanding at the time.

I'll take the time to look into it again!
